apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-nodeapp
  labels:
    app: deploy-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-app
  template:
    metadata:
      labels:
        app: deploy-app 
    spec:
      containers:
      - name: nodeserver
        image: thilina9718/deploy-app:latest
        ports:
        - containerPort: 3000