name: CI

on:
  - push
  - pull_request
  
jobs:
  job1:
    runs-on: ubuntu-latest
    name: build discover and deploy
    steps:
      - uses: actions/checkout@v2
      - name: Start minikube
        uses: medyagh/setup-minikube@latest
      # now you can run kubectl to see the pods in the cluster
      - name: Try the cluster!
        run: kubectl get pods -A
      - name: Build image
        run: |
          export SHELL=/bin/bash
          eval $(minikube -p minikube docker-env)
          docker build -f ./Dockerfile -t thilina9718/deploy-app:latest .
          echo -n "verifying images:"
          docker images 
      - name: Deploy to minikube
        run: |
          kubectl apply -f deployment.yml
      - name: Test service URLs
        run: |
          minikube service list
          minikube service service-nodeapp --url
          echo -n "------------------opening the service------------------"
          curl $(minikube service service-nodeapp --url)/version
